- docs/spec/api/disclaimer.md
I'm not 100% sure whether the `docs/spec/api/disclaimer.md` file is required. If it is then it certainly shouldn't reference the IIIF (from where it was copied I assume) so this PR fixes that.
> Remove IIIF history

- docs/spec/api/0.1/recommendations_for_activity_streams.md
There is a mix of one and two spaces after full stops at the end of sentences. This commit standardizes to a single space after each full stop.
> Standardize spacing after full stops

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Just removes trailing line-end spaces. No change to content or formatting when rendered.
This makes the markdown easier to work with for folks like me who have their editor set to remove trailing spaces.
> Tidy: Remove trailing spaces

- docs/spec/api/0.1/recommendations_for_activity_streams.md
The current spec defines a role:
> Entity Metadata Developer: Software developers that create applications and tools that help consumers connect to entity metadata from providers. The developer may be associated with the provider, consumer, or a third party.
that isn't used elsewhere in a meaningful way like Providers and Consumers. I think it simplifies things to simply delete this definition and refer to developers simply as developers one other time the term was used.
This PR makes no change to substance of the API.
> Remove unused defn of Entity Metadata Developers

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Trivial fix of link typo 2199 -> 2119. No change to content or meaning.
> Correct RFC2119 link

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Small working change, not change to normative language
> Avoid implying always multiple reasons for caching

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Changes instances of backticked literals with quotes (e.g. `"id"`) to use simply backticks (e.g. `id`) in order to be somewhat more consistent.
(We still have considerable inconsistency with terms in italics and terms in backticks that will need to be sorted out at some stage.)
> Remove quote for backticked (literal) items

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Have created #39, #39, #40, #41, #42 and removed the "TO-DO" notes in the draft. Also did some tidy with line spaces and left-over mention of "Entity Metadata Developers" 
No change to substance of specification
> Remove several to-dos that are now issues, tidy

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Trivial typo fix: authoritity -> authority
> Fix typo "authoritity"

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Add missing words "use cases" and also "efficiently" to make the point that these use cases can be fulfilled without patch but are more efficient with it.
> Fix language for entity patch

- docs/spec/api/0.1/recommendations_for_activity_streams.md
I think the section needs a sentence of introductions.
Fixes type `ordered_items` to `orderedItems`
> Add intro sentence for entity level structures, fix typos

- docs/spec/api/0.1/recommendations_for_activity_streams.md
* fix broken `#notifications` link
* try for better sequence in description of change notification: change -> notification, notification is Activity, Activities MUST and MAY have certain information
* minor tweak to layout of example
> Fix link, improve entity change notification description

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Per discussion https://wiki.lyrasis.org/display/LD4P3/2022-09-12+Meeting%3A+Continue+to+Review+Document attempt to adjust to use "Entity Set" as the set of entities for which an Entry Point makes metadata available for. Replace the term "Entity Metadata Collection".
> Try using Entity Set instead of Entity Metadata Collection

- docs/spec/api/0.1/recommendations_for_activity_streams.md
Fixes #60 
* add descriptions of `next` (required) and `prev` (optional)
* changes descriptions of `first` and `last` to allow URI or JSON object per discussion in
> Add next and prev, adjust first and last

- docs/0.1/index.md
Data Providers SHOULD include `published` on the the activity for when the activity was made available in the stream, and `updated` on the object for when the change to the entity actually occurred.
Removed `published` date from OrderedCollections, etc. because we're focusing on dates of Activities, when they were published and when the change actually occurred.
> Published and Update date properties

- docs/0.1/index.md
We've removed Split and Merge as Activity types, but we want domain experts wondering how to address these scenarios to refer to the deprecate section.
> Edits to how we refer to Split/Merge use cases

- docs/0.1/index.md
Move those who were active early on but not recently into the Acknowledgement so that we properly reflect editorial responsibility, fixes #80
> Trim editors to currently active list, acknowledge others

- docs/0.1/index.md
Fixes #125 
Also removes excess formatting of "Entity Metadata Management" that isn't defined as a term and looks messy with the extra formatting
> Extension contexts must go first, fix formatting

- docs/0.1/index.md
@NancyJean This makes it consistent with elsewhere in the document (and styling on the Getty's web site, etc)
> Capitalize Getty Vocabularies

- docs/0.1/index.md
@NancyJean Throughout the rest of the document, "human readable" is used without a hyphen. (I don't care either way, as long as it's consistent.)
> Make styling of "human readable" consistent

- docs/0.1/index.md
@NancyJean It's my understanding that "e.g." and "etc." aren't supposed to be used together, as "e.g" indicates that a list that follows inherently consists of an incomplete set of examples
> Remove superfluous et ceteras

- docs/0.1/index.md
@NancyJean I'm assuming that "application users" in the first sentence are the same as "end users" in a later sentence, so using the same phrase here makes clear that we're not talking about machines as users — right?
> Clarify which users 1.2.2 is about

- docs/0.1/index.md
@NancyJean I'm assuming these definitions should both start with "an", rather than "an" and "any". Unless there's something I'm missing here!
> Make language consistent in 1.3.1

- docs/0.1/index.md
@NancyJean I've added a conjunction here, but it could also be fixed with a semicolon. 
Or these could be two separate sentences. 
Or "As implementations _MAY_{:.strong-term} use other properties from Activity Streams or elsewhere for extension, consumers _SHOULD_{:.strong-term} ignore any properties not defined in this specification that they don't understand" if we want this to explicitly state a causal link between the two statements.)
> Fix grammar in 2.1

- docs/0.1/index.md
@NancyJean The phrase "reflecting the deprecation" is placed awkwardly and makes this sentence hard to read. I think it's not needed and is stated more clearly later on in this section.
> Simplify first sentence in 4.3

- docs/0.1/index.md
@NancyJean This is mostly to make initial references to specific activity streams clearer, and keep names in sync with how they're represented elsewhere in the document
> Minor clarifications to 6.1 language

- docs/0.1/index.md
Follow-on from #165 and @sfolsom's note:
> We have every combination \`\`, \_\_{:.term}, and unformatted.
This PR changes the change the one example of "Ordered Collection" and the one example of "Ordered Collection Page" to terms that are linked.
> Use either backticks of terms for OrderedCollection[Page]

- docs/0.1/index.md
Minor clarifying additions for consistency across this section.
In addition: I'm not sure I understand the difference(s) between the first line of 4.1 and the subsection "Create vs. Add" —
4.1 "A new entity SHOULD have an Entity Change Activity with a type of either Create or Add."
Create vs. Add: "An entity appearing in an Entry Point stream for the first time MUST use Activity type Create and/or Add."
Do both statements apply to "an entity appearing in an Entry Point stream for the first time"? If so, should 4.1 lead off with that phrase ("An entity appearing in an Entry Point stream for the first time"), as I initially misread it as being about entities new only to the stream (and not entities new to the dataset, as in the last scenario under Create vs. Add)?
(I'm also unclear about …
> Clarify language in 4.1

- docs/0.1/index.md
Reference terminology section at first appearance of document-specific phrases: "Entity Metadata Provider", "Entity Metadata Consumer"
> Add links to section 1

- docs/0.1/index.md
"informed" hopeful shows that the implementations happened before the spec was created. Also added links to their streams/tech pages.
> Make clearer the relationship between spec and Getty and LOC
