docs/_includes/api/links.md, docs/_sass/emm/api-spec.scss, docs/_sass/emm/base.scss, docs/spec/api/0.1/recommendations_for_activity_streams.md
There is more refinement to be done in the Producing Entity Change Sets section, but this gives a good start on it.  Several TODOs and QUESTIONs sprinkled throughout.
=> add steps to produce an Activity Stream

docs/spec/api/0.1/recommendations_for_activity_streams.md
Trivial to change to use RFC2119 word (CAN is not one), no change of meaning intended
=> Use MAY as RFC2119 word

docs/spec/api/0.1/recommendations_for_activity_streams.md
=> Minor formatting and typo fixes

docs/spec/api/0.1/recommendations_for_activity_streams.md
Instead of defining authorities, controlled vocabularies, etc. we decided to define entities more broadly.
=> Add definition for Entities.md

docs/spec/api/0.1/recommendations_for_activity_streams.md
Fixes #11 and corrects use of `@context` in examples throughout
=> Fix @context and improve description

docs/spec/api/0.1/recommendations_for_activity_streams.md
Clarify use of `partOf` per discussion in https://github.com/LD4/entity_metadata_management/issues/12
=> Clarify use of partOf

README.md, docs/spec/api/0.1/recommendations_for_activity_streams.md
Fixes #18. Changes API name and associated wording
=> Use EMM API name

docs/spec/api/0.1/recommendations_for_activity_streams.md
=> Use only EMM context which imports AS context

docs/spec/api/0.1/recommendations_for_activity_streams.md
Reword to tighten description of `url` property on _Entry Point_.
=> Tighten url description

docs/spec/api/0.1/recommendations_for_activity_streams.md
Typo fix, no change to meaning
=> Fix typo in totalItems

docs/spec/api/0.1/recommendations_for_activity_streams.md
This section was missing content. Have attempted to describe the key terms in relation to the EMM API
=> Add description of key terms from Activity Streams

docs/spec/api/0.1/recommendations_for_activity_streams.md
Addresses https://github.com/LD4/entity_metadata_management/issues/59#issuecomment-1258350042, related to #59
=> Fix published to updated on Activity objects

docs/spec/api/0.1/recommendations_for_activity_streams.md
Attempts to address https://github.com/LD4/entity_metadata_management/issues/31
=> Replaced Notification language with Activities

docs/spec/api/0.1/recommendations_for_activity_streams.md
Addresses https://github.com/LD4/entity_metadata_management/issues/51
=> Removed instrument from first example now that it is optional

docs/spec/api/0.1/recommendations_for_activity_streams.md
Based on our conversations about a three-state consumer focused stream.
=> Start of type changes

docs/spec/api/0.1/recommendations_for_activity_streams.md
minor language and formatting updates
=> Minor updates

docs/spec/api/0.1/recommendations_for_activity_streams.md
Still need to work out split and merge scenarios.
=> Making clear the distinction between Deletes and Deprecation

docs/0.1/index.md
While important steps in entity management, we didn't have a clear direction for how to handle more complicated scenarios, e.g. partial splits, partial merges. We will defer this to a future round of specification development. The spec, as it is written, will will provision for full Splits and Merges using a combination of Deprecate and Create. For partial splits/merges (where the existing entity continues to exist), Update and Create can be used.
=> Removing Merge and Split Activity Types

docs/0.1/index.md
Fixes #96
Have done a read and pass through the intro sections and hope to address the issues in #96
=> Tighten intro

docs/0.1/index.md
Fixes #100, removes all mention of RDF Patch
=> Remove discussion of RDF Patch

docs/0.1/index.md
Fixes #102, quite a big change with section changes too
=> Remove standalone activities, change section structure

docs/0.1/index.md
Fix tagging of a few RFC2119 terms and close <a ..> tags
=> Fix a little RFC2119 formatting

docs/0.1/index.md
=> Make first and last SHOULD

docs/0.1/index.md, docs/_includes/api/links.md
=> WIP: DO NOT MERGE YET - Add missing property definitions

docs/0.1/index.md, docs/_includes/api/links.md
Reverts LD4/entity_metadata_management#117
=> Revert "WIP: DO NOT MERGE YET - Add missing property definitions"

docs/0.1/index.md
=> Add missing property definitions

docs/0.1/index.md
Fixes #98. Went through and checked all example titles use consistent form. Two minor fixes
=> Fix a couple of captions

docs/0.1/index.md
@eichmann @kefo I made a first pass at starting Appendices. I moved Section 5 to Appendix A. Section 6 can become Appendix B.
=> Turn section 5 into Appendix A

docs/0.1/index.md
Fixes: https://github.com/LD4/entity_metadata_management/issues/93
=> Update to Deprecate and related Activities.

docs/0.1/context.json, docs/0.1/index.md, docs/_includes/api/links.md
=> Require Activity Steams @context, recommend EMM @context

README.md, docs/0.1/context.json, docs/0.1/examples/my-collection/full-cache/entry-point.json, docs/0.1/examples/my-collection/notifications/document/cd1-add.json, docs/0.1/examples/my-collection/notifications/document/cd10-m1.json, docs/0.1/examples/my-collection/notifications/document/cd10-m2.json, docs/0.1/examples/my-collection/notifications/document/cd10-m3.json, docs/0.1/examples/my-collection/notifications/document/cd10-merge.json, docs/0.1/examples/my-collection/notifications/document/cd2-create.json, docs/0.1/examples/my-collection/notifications/document/cd3-remove.json, docs/0.1/examples/my-collection/notifications/document/cd4-delete.json, docs/0.1/examples/my-collection/notifications/document/cd5-update.json, docs/0.1/examples/my-collection/notifications/document/cd6-d1.json, docs/0.1/examples/my-collection/notifications/document/cd6-d2.json, docs/0.1/examples/my-collection/notifications/document/cd6-deprecate.json, docs/0.1/examples/my-collection/notifications/document/cd7-deprecate.json, docs/0.1/examples/my-collection/notifications/document/cd8-deprecate.json, docs/0.1/examples/my-collection/notifications/document/cd9-s1.json, docs/0.1/examples/my-collection/notifications/document/cd9-s2.json, docs/0.1/examples/my-collection/notifications/document/cd9-s3.json, docs/0.1/examples/my-collection/notifications/document/cd9-split.json, docs/0.1/examples/my-collection/notifications/entry-point.json, docs/0.1/examples/my-collection/notifications/sets/1.json, docs/0.1/examples/my-collection/notifications/sets/2.json, docs/0.1/examples/my-collection/notifications/sets/3.json, docs/0.1/examples/my-collection/notifications/sets/4.json, docs/0.1/examples/my-collection/partial-cache/entry-point.json, docs/0.1/index.md
=> Change location to https://emm-spec.org/0.1/

docs/0.1/index.md
This had Dave's chages but not LOC changes
=> Section 6 - Merge in Dave's changes

docs/0.1/index.md
I've been sitting on this one a while.  I have long felt each of the special Things needed at least a sentence definition/introduction.  That's the main thrust of this pull request.  As before, wordsmith away, I've gots no pride.
=> Adding definitions.

docs/0.1/index.md
=> Spell out EMM

docs/0.1/index.md
Let me know if the pseudocode is overwrought.  Wordsmith away; I have no pride.
=> Finagling LC processing section.

docs/0.1/index.md
=> Reword section 1.2.1

docs/0.1/index.md
=> Remove extraneous sentence in 1.3.3

docs/0.1/index.md
Reverts LD4/entity_metadata_management#143
=> Revert "Capitalize initial letters in Entity Metadata Provider(s)"

docs/0.1/index.md
@NancyJean this merely removes an unnecessary "the"
=> Remove superfluous article

docs/0.1/index.md
@NancyJean Another bizarrely small change!
=> Make formatting consistent for Create

docs/0.1/index.md
As per yesterday's discussion on zoom. 
(Sorry, galleries!)
=> Remove mentions of galleries

docs/0.1/index.md
@NancyJean Tweaked language and added formatting where needed
=> Make use of Activity types consistent in 4.3

docs/0.1/index.md
=> Clarify language in appendix A

docs/0.1/index.md
Based on discussion in today's meeting.
=> Making clear earlier what we mean by "new"

docs/1.0/context.json, docs/1.0/index.md, docs/_config.yml
Merging will release 1.0. Fixes #174
=> Prepare for 1.0 release

README.md
Github readme is out of date...
=> Update README.md to reflect v1.0
